### ISSUE TITLE
前端代码都是静态的嘛 从master拉下来的代码没看到有请求后端的请求啊

### ISSUE THREAD

**Issue by ronzheng6** [llldddbbb/dbblog#1]

**Comment by llldddbbb** [comment]
有请求的呀，你看看httpRequest.js

**Comment by ronzheng6** [comment]
那是用axios封装的请求工具类吧 具体的接口请求地址都没看见一个啊

发自我的 iPhone

**Comment by daowolf** [comment]
哥们你们前端登录账号密码是多少？是admin，admin么
我使用密码错误

**Comment by llldddbbb** [comment]
更新下代码，重新执行dbblog_sys_user.sql，账号密码为admin，123456

**Comment by llldddbbb** [comment]
代码里不是很多么？比如
 this.$http({
        url: this.$http.adornUrl('/operation/recommends'),
        method: 'get',
        params: this.$http.adornParams()
      }).then(({data}) => {
        if (data && data.code === 200) {
          this.recommendList = data.recommendList
          this.topRecommend = this.recommendList.shift()
        }
      })

**Comment by daowolf** [comment]
3ks

**Comment by ronzheng6** [comment]
看到了 thanks 

发自我的 iPhone
